// Generated by CoffeeScript 1.3.3
(function() {
  var initialize, markers, plot;

  markers = {};

  plot = function(location, user) {
    var latLng;
    latLng = new google.maps.LatLng(location.x, location.y);
    if (user.name in markers) {
      return markers[user.name].setPosition(latLng);
    } else {
      return markers[user.name] = new StyledMarker({
        styleIcon: new StyledIcon(StyledIconTypes.MARKER, {
          color: user.color
        }),
        position: latLng,
        map: map
      });
    }
  };

  initialize = function() {
    var options;
    options = {
      center: new google.maps.LatLng(43.4879158266, -80.5462864345),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      zoom: 15
    };
    window.map = new google.maps.Map(document.getElementById("map_canvas"), options);
    /*host = "198.58.106.27"
    port = 8080
    socket = new WebSocket("ws://" + host + ":" + port + "/")
    socket.onopen = ->
      for i in [1..6]
        socket.sendJSON {"SUBSCRIBE": "testusr#{i}"}
    socket.onmessage = (message) ->
      data = this.decodeJSON(message)
      if data
        plot(data.location, data.user)
    */

    plot({
      x: 43.4879158266,
      y: -80.5462864345
    }, new User('abc'));
    return plot({
      x: 43.4879158266,
      y: -80.5562864345
    }, new User('abd'));
  };

  window.map = void 0;

  google.maps.event.addDomListener(window, "load", initialize);

}).call(this);
