// Generated by CoffeeScript 1.4.0
(function() {
  var initialize, markers, plot;

  markers = {};

  plot = function(location, user) {
    var latLng;
    latLng = new google.maps.LatLng(location.x, location.y);
    if (user.name in markers) {
      return markers[user.name].setPosition(latLng);
    } else {
      return markers[user.name] = new StyledMarker({
        styleIcon: new StyledIcon(StyledIconTypes.MARKER, {
          color: user.color
        }),
        position: latLng,
        map: map
      });
    }
  };

  initialize = function() {
    var host, options, port, socket;
    options = {
      center: new google.maps.LatLng(43.4879158266, -80.5462864345),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      zoom: 15
    };
    window.map = new google.maps.Map(document.getElementById("map_canvas"), options);
    host = "198.58.106.27";
    port = 7381;
    socket = new Socket("ws://" + host + ":" + port + "/.json");
    socket.onopen = function() {
      var i, _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 7; i = ++_i) {
        _results.push(socket.sendJSON(["SUBSCRIBE", "testusr" + i]));
      }
      return _results;
    };
    return socket.onmessage = function(message) {
      var data;
      data = this.decodeJSON(message);
      if (data) {
        return plot(data.location, data.user);
      }
    };
  };

  window.map = void 0;

  google.maps.event.addDomListener(window, "load", initialize);

}).call(this);
